language: scala
scala:
  - 2.12.6
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - dwestheide@googlemail.com
jdk:
  - oraclejdk8
script:
  - sbt clean coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
